name: lite_code_editor
description: "Lightweight Flutter code editor with syntax highlighting, auto-indent, autocomplete, and line selection. Zero external dependencies."
version: 0.1.1
homepage: https://github.com/DolphH12/lite_code_editor
repository: https://github.com/DolphH12/lite_code_editor
issue_tracker: https://github.com/DolphH12/lite_code_editor/issues

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

topics:
  - editor
  - code
  - syntax-highlighting
  - ide
  - dart